# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cody's Collection
email: codyrodgers92@icloud.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codydalerodgers.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: codydalerodgers/personal-blog
github: [metadata]

r05:        <image class="rating-images" src="/assets/images/half.png"></image>
r1:         <image class="rating-images" src="/assets/images/one.png"></image>
r15:        <image class="rating-images" src="/assets/images/onehalf.png"></image>
r2:         <image class="rating-images" src="/assets/images/two.png"></image>
r25:        <image class="rating-images" src="/assets/images/twohalf.png"></image>
r3:         <image class="rating-images" src="/assets/images/three.png"></image>
r35:        <image class="rating-images" src="/assets/images/threehalf.png"></image>
r4:         <image class="rating-images" src="/assets/images/four.png"></image>
r45:        <image class="rating-images" src="/assets/images/fourhalf.png"></image>
r5:         <image class="rating-images" src="/assets/images/five.png"></image>
ip:         <span style="white-space:nowrap;"><image class="emoji" src="/assets/images/stars.png">(in progress)<image class="emoji" src="/assets/images/stars.png"><span>
rw:         <abbr title="Rewatched"><image class="emoji" src="/assets/images/repeat_arrows.png"></image></abbr>
sh:         <abbr title="Short"><image class="emoji" src="/assets/images/short.png"></image></abbr>
tr:         <abbr title="Theatre"><image class="emoji" src="/assets/images/theater.png"></image></abbr>
cy:         <div class="currentYear" hidden>currentYear</div>

social:
  -
    website: twitter
    url: https://twitter.com/
    name: twitter
    username: codyrodgers92
  -
    website: instagram
    url: https://instagram.com/
    name: instagram
    username: codydalerodgers
  -
    website: github
    url: https://github.com/
    name: github
    username: codyrodgers92
  -
    website: linkedin
    url: https://linkedin.com/in/
    name: linkedin
    username: cody-rodgers-9554ba58

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-thumbnail-generator
  - jekyll-asset-path-plugin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Cody Rodgers"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Cody Rodgers"

collections:

    books:
      output: true
      permalink: /books/:path/

    films:
      output: true
      permalink: /films/:path/

    games:
      output: true
      permalink: /games/:path/

    podcasts:
      output: true
      permalink: /podcasts/:path/

    shows:
      output: true
      permalink: /shows/:path/

gallery:
  - file: lotr_poster.png
    title: Lord of the Rings Poster
  - file: second-image.jpg
    title: Second image file

thumbnail_gallery:
  width:  300
  height: 180


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
